(in-package :pd2rs-db)

(defun gethashtable ()
  (let ((hash (make-hash-table)))
    (mapcar #'(lambda (x) (setf (gethash (cadr x) hash) (car x)))
	    '(("1stvn" "1st.VN") ("3dclan" "3D!Clan") ("3dmax" "3DMAX")
	      ("4 friends chrillee" "4FC") ("abc" "ABC") ("absolute legends" "aL")
	      ("aceonline" "Ace") ("adversa" "Adversa") ("aeonsports" "AEON")
	      ("ahead gaming" "Ahead.kz") ("al academy" "aL.Acad") ("anarchist" "aNa")
	      ("aposis gaming" "Aposis") ("art" "ART") ("artyk" "Artyk") ("aspera" "aSpera")
	      ("aurochs" "Aurochs") ("ave" "Ave") ("awake" "Awake") ("baguette" "Baguette")
	      ("bien hoa assassins" "BHA") ("bx3 esports club" "BX3") ("cascade" "cSc")
	      ("chainsstack" "C.SK") ("clan poland" "Clan Pl") ("come" "CoMe") ("cnb" "CNB")
	      ("complexity gaming" "coL") ("copenhagen wolves" "Wolves")
	      ("counter logic gaming" "CLG") ("darer" "Darer") ("dddota" "DD")
	      ("denial esports" "Denial") ("dreamz" "Drmz") ("druidz" "DRz")
	      ("dts gaming" "DTS") ("dts2010" "DTS2010") ("duskbin" "Duskbin")
	      ("dust" "DuSt") ("duza" "Duza") ("eclypsia" "EC") ("ehome" "EHOME")
	      ("energy esports" "Energy") ("eosin" "E+4") ("evil geniuses" "EG")
	      ("evo" "evo^") ("experience" "xP") ("eyesonu" "EYES") ("fastgg" "FastGG")
	      ("firstdeparture" "FD") ("flash" "Flash") ("flipside tactics" "[F.3]")
	      ("fnatic" "Fnatic") ("fnatic.eu" "Fnatic.EU") ("fnatic.na" "Fnatic.NA")
	      ("forlove" "FL") ("for our utopia" "fOu") ("freedom of the action" "fota")
	      ("fubar" "FUBAR") ("fxopen e-sports" "FXO") ("gabe pls" "PLS")
	      ("gamer university" "GU") ("gamersleague" "GL") ("gameware" "GW")
	      ("gdteam" "[GD]") ("gizmo" "GizMo") ("gosugamers" "GG") ("grats tho" "GraTs")
	      ("h2k gaming" "H2k") ("heart get together" "HGT") ("hwa" "HWA")
	      ("iccup" "iCCup") ("ice" "Ice") ("ice climbers" "IC") ("ideal" "iDeal")
	      ("imaginary gaming" "imG") ("imperium" "IMP") ("impervious" "Imp")
	      ("infernity gaming" "iNG") ("infinity" "Inf") ("insight esports" "Insight")
	      ("invasion" "Invasion") ("invictus gaming" "iG") ("isurus" "Isurus")
	      ("it's gosu esports" "It's Gosu") ("joenet" "JoeNet") ("kaipi" "KP")
	      ("kawaii" "Kawaii") ("keita gaming" "Keita") ("lgd gaming" "LGD")
	      ("lgd international" "LGD.int") ("lions pride" "eL'Pride")
	      ("lowlandlions" "LLL") ("make dream" "MD") ("meet your makers" "MYM")
	      ("mineski infinity" "Mineski") ("minion!" "Minion") ("mith.trust" "MiTH")
	      ("mme" "mMe") ("moonlight united" "MU") ("mortal team work" "mTw")
	      ("moscow five" "M5") ("mousesports" "mouz") ("msi-evogt" "MSI")
	      ("mufc" "MUFC") ("mvp" "MVP") ("natural 9" "N9") ("natus vincere" "Na`Vi")
	      ("neolution" "NeoES") ("neolution.ac" "Neo.ac") ("neolution.int" "Neo.int")
	      ("neolution.ino" "Neo.ino") ("neolution.th" "Neo.th") ("netolic" "NTL")
	      ("nevo" "NeVo") ("nex impetus" "neX-I") ("next.kz" "NEXT")
	      ("nirvana" "Nirvana") ("nirvana.int" "Nirvana.int") ("njkids" "NJ&K")
	      ("no tidehunter" "nth") ("online kingdom" "OK") ("oot" "OoT")
	      ("orange" "Orange") ("oslik gaming" "OsG") ("pacific" "Pacific")
	      ("pacific2" "Pacific 2") ("pain" "paiN") ("painint" "paiN.int")
	      ("pandarea" "PanDa") ("poseidon" "PSN") ("potm bottom" "PotM")
	      ("power rangers" "PR") ("property" "prOp") ("pulse" "Pulse")
	      ("qpad dragons" "QPAD") ("quantic gaming" "Quantic") ("qwert12345" "QWERT")
	      ("rat in the dark" "rat") ("rattlesnake" "RSnake")
	      ("rattlesnake.int" "RS.int") ("revenge" "Rvg") ("rigg3d" "r3D")
	      ("risingstars" "RStars") ("root gaming" "ROOT") ("rox" "RoX")
	      ("scaryfacez" "SFZ") ("scythe gaming" "Scythe") ("seasonone" "SOne")
	      ("sequential" "sqL") ("shakira" "Shakira") ("sigma.int" "S.int")
	      ("sk gaming" "SK") ("skanes elit" "Skne") ("skyhigh" "SH")
	      ("speed gaming" "Speed") ("startale" "ST") ("storm games clan" "SGC")
	      ("sushiandyasha" "SnY") ("svenhunterz" "Shz") ("sweetnchina" "SnC")
	      ("swyc" "SWYC") ("symphony" "Sym4ny") ("tba" "TBA") ("tbd" "TBD")
	      ("tcm-gaming" "TCM") ("team aaa" "aAa") ("team dignitas" "Dignitas")
	      ("team dk" "DK") ("team empire" "Empire") ("team infused" "Infused")
	      ("team life" "Life") ("team liquid" "Liquid") ("team menace.fi" "Menace")
	      ("team one" "ONE") ("team zenith" "Zenith") ("tera gaming" "Tera")
	      ("terrible terrible damage" "TTD") ("the alliance" "[A]") ("the retry" "TR")
	      ("titan esports" "Titan") ("tnc" "TnC") ("tongfu" "TongFu")
	      ("top igrokai" "top") ("ttb" "TTB") ("turtle masters" "Turtle")
	      ("tyloo" "TyLoo") ("uebelst" "uebelstG") ("ultimate" "ULTI")
	      ("underrateds" "UR") ("vici gaming" "VG") ("virtualthrone" "VTG")
	      ("virtus.pro" "VP") ("virus gaming" "Virus") ("vivacity" "Vivacity")
	      ("vt gaming" "vTG") ("w4sp" "w4sp") ("we haz asian" "WhA")
	      ("western wolves" "WW") ("wild honey badgers" "WHB") ("world elite" "WE")
	      ("wpc" "WPC.A") ("xx5" "XX5") ("youboat" "yB") ("z4" "Z4") ("zero" "Zero")
	      ("znation" "zNation") ("zrage" "zRAGE")))
    hash))
